### ISSUE TITLE
'Long' loading time for svg

### ISSUE THREAD

**Issue by SaturnusDJ** [ExperienceLovelace/lovelace-floorplan#18]
Seems like it can take a few seconds for the svg to load, specifically on mobile devices.
Is there a workaround? Better caching/preloading possible?

**Comment by lujiashun1** [comment]
yes  I have the same problem

**Comment by exetico** [comment]
Hi, 

Are you still experiencing the same problem? I'm on a fast connection, and have not noticed any problems.

**Comment by exetico** [comment]
Hi all,

It's handled much better in our new version - so I'll recommend you to give it a try.

I would like to ask all of you to move forward to [ha-floorplan](https://github.com/ExperienceLovelace/ha-floorplan). It's almost ready. If you need inspiration, check out the three examples in the docs. But please note that we're still missing a good amount of things in the docs. I've enabled the "Discussion" tab in the new repo, so fell free to ask for support if needed. I'll try and use that, to improve the docs, too. (_You'll currently find "Work in progress"-like strings on most of the pages_).
