### ISSUE TITLE
Floorplan misplaced

### ISSUE THREAD

**Issue by koldogut** [ExperienceLovelace/lovelace-floorplan#27]
Hi all, sorry but I'm a bit newbee.  I've tried almost everything and double checked SVG format, size, position, etc, but I'm not able to center rooms on the floorplan. They are unscaled and moved to the right upper corner (res. 1920x1080 px). ¿Any ideas? here you are the code

 - config:
      image: /local/floorplan/planta_baja.svg?v=1.1.15
      log_level: error
      more_info: true
      rules: 
       - action:
          service: homeassistant.toggle
         element: light.terraza
         entity: light.terraza
         image_template: '/local/floorplan/terraza_${entity.state}.svg'
         state: image
       - action:
          service: homeassistant.toggle
         element: light.salon
         entity: light.salon
         image_template: '/local/floorplan/salon_${entity.state}.svg'
         state: image
       - action:
          service: homeassistant.toggle
         element: light.cocina
         entity: light.cocina
         image_template: '/local/floorplan/cocina_${entity.state}.svg'
         state: image
       - action:
          service: homeassistant.toggle
         element: light.estudio
         entity: light.estudio
         image_template: '/local/floorplan/estudio_${entity.state}.svg'
         state: image
    type: 'custom:floorplan-card'

![My_Floorplan](https://user-images.githubusercontent.com/43078880/77992352-326a4c00-7326-11ea-91fc-9eaf7cbcf472.GIF)

**Comment by SBerg1980** [comment]
I had the same thing i changed the version number everytime i change the svg ?v=1.1.15

**Comment by damiano75** [comment]
Same thing here: I used a bulb svg icon, but it was always in the left upper corner, then in Inkscape I right-clicked on the bulb icon, selected group action and saved all. Now I have the icon in the right place, but it has the svg icon dimension, not the dimension I used in inkscape

**Comment by exetico** [comment]
Hi, 

I've just pushed the first "official" version of Lovelace floorplan. Are you guys still able to reproduce the issue? 

If so, kindly let me know.

**Comment by exetico** [comment]
Hi all,

I would like to ask all of you to move forward to [ha-floorplan](https://github.com/ExperienceLovelace/ha-floorplan). It's almost ready. If you need inspiration, check out the three examples in the docs. But please note that we're still missing a good amount of things in the docs. I've enabled the "Discussion" tab in the new repo, so fell free to ask for support if needed. I'll try and use that, to improve the docs, too. (_You'll currently find "Work in progress"-like strings on most of the pages_).
