### ISSUE TITLE
README links to examples are broken

### ISSUE THREAD

**Issue by tv42** [ExperienceLovelace/lovelace-floorplan#46]
https://github.com/ExperienceLovelace/lovelace-floorplan/tree/929efccd623cd1aa72b264cc6aacfeb750020e4f#floorplan-examples

links to e.g. https://github.com/pkozul/lovelace-floorplan/tree/master/www/floorplan/examples/simple
which does not exist.

This does exist: https://github.com/ExperienceLovelace/lovelace-floorplan/tree/master/examples/simple

You should be able to use just a relative link.

**Comment by exetico** [comment]
Hi 🎉

The next version of Floorplan are almost ready for the public. Our documentation are still in the scope - but that's almost the only things which are missing.

Please take a look 😀
https://github.com/ExperienceLovelace/ha-floorplan

And oh; Thanks you for reporting the issue.

**Comment by exetico** [comment]
Fixed with https://github.com/ExperienceLovelace/lovelace-floorplan/commit/f588a69e927444437dce3366f069db38db9b06cb
