### ISSUE TITLE
SVG files not available for download

### ISSUE THREAD

**Issue by terenceng81** [ExperienceLovelace/lovelace-floorplan#47]
Hi,

The download links like broken, any idea i could download them for testing purpose?

Thanks
Terence

**Comment by terenceng81** [comment]
Got it, I found them here

https://github.com/ExperienceLovelace/ha-floorplan/tree/master/docs/_docs/floorplan/examples/home

**Comment by exetico** [comment]
Please check https://experiencelovelace.github.io/ha-floorplan/ - we're on the way of migration to that :-) Please check the examples in the docs (it' still being working on), and the HA community :-) (Check the post for more info)

https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489/330

**Comment by terenceng81** [comment]
> Please check https://experiencelovelace.github.io/ha-floorplan/ - we're on the way of migration to that :-) Please check the examples in the docs (it' still being working on), and the HA community :-) (Check the post for more info)
> 
> https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489/330

Thanks Exetico for the efforts to make it happens.

I have tried to download the two files below but unsuccessful, it seems to be already removed.
https://github.com/ExperienceLovelace/ha-floorplan/blob/master/docs/_docs/floorplan/examples/home/light_off.svg
https://github.com/ExperienceLovelace/ha-floorplan/blob/master/docs/_docs/floorplan/examples/home/light_on.svg

Would you mind to share with me where I can download the files?

Thanks!
Terence

**Comment by exetico** [comment]
Hi again 👋

They are working just fine on my device👍?

https://github.com/ExperienceLovelace/ha-floorplan/tree/master/docs/_docs/floorplan/examples/home

Try and browse to this directory, and download them one by one. If you're
still facing issue, just download the main repo, and browse to docs > _docs
> floorplan > examples, and pick up the files you need from each
subdirectory 😀

https://github.com/ExperienceLovelace/ha-floorplan/archive/master.zip

//Tobias (from mobile)

ons. 30. dec. 2020 18.51 skrev terenceng81 <notifications@github.com>:
