### ISSUE TITLE
"Simple" example .svg error

### ISSUE THREAD

**Issue by nagydavid** [ExperienceLovelace/lovelace-floorplan#48]
The example .svg files throw an error. 
error on line 2 at column 6: XML declaration allowed only at the start of the document

**Comment by exetico** [comment]
Hi

Please check our new solution:
https://github.com/ExperienceLovelace/ha-floorplan

The SVG are corrected there, and lovelace-floorplan are almost departured by now. The new version includes many good improvements ☺️👍
